<?php
/**
 *  Copyright 2011 Wordnik, Inc.
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 *
 * @package default
 */


/**
 * $model.description$
 *
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 *
 */

/**
 * source code generated by http://restunited.com using Swagger Codegen
 * for any feedback/issue, please send to feedback{at}restunited.com
 *
 * swagger-codegen: https://github.com/wordnik/swagger-codegen
 */

/**
 * APIClient.php
 */
namespace Sexyoung\ImaggaLaravel\models;

class Cropping {

	static $swaggerTypes = array(
		'target_height' => 'int',
		'target_width' => 'int',
		'x1' => 'int',
		'x2' => 'int',
		'y1' => 'int',
		'y2' => 'int'

	);

	static $attributeMap = array(
		'target_height' => 'target_height',
		'target_width' => 'target_width',
		'x1' => 'x1',
		'x2' => 'x2',
		'y1' => 'y1',
		'y2' => 'y2'

	);

	/**
	 * Target height
	 */
	public $target_height; // int
	/**
	 * Target width
	 */
	public $target_width; // int
	/**
	 * X1
	 */
	public $x1; // int
	/**
	 * X2
	 */
	public $x2; // int
	/**
	 * Y1
	 */
	public $y1; // int
	/**
	 * Y2
	 */
	public $y2; // int
}
